version: '3.8'

services:
  backend_box:
    image: backend_box
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/feedback_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    networks:
      - feedback-network

  mysql-container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=feedback_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - feedback-network

networks:
  feedback-network:
    driver: bridge

volumes:
  mysql-data: